In [3]:
import duckdb
import pandas as pd

server="oss.resilientservice.mooo.com"
bucket= "resilentpublic"

con = duckdb.connect()

In [10]:
hs2s_base="latest/tijuana/sd_apcd_air/h2s"
hs2name_pattern="apcd_h2s_*.parquet"
hs2name_pattern="*.parquet"
hs2_files=f"https://{server}/{bucket}/{hs2s_base}/{hs2name_pattern}"

hs2file="https://oss.resilientservice.mooo.com/resilentpublic/latest/tijuana/sd_apcd_air/h2s/apcd_h2s_2023.parquet"
hs2_data=con.read_parquet(hs2file).df()
hs2_data
#hs2_data.sql(f'SELECT * from read_parquet("{hs2_files}")').show()

,SiteName,Latitude,Longitude,AgencyName,LongName,Parameter,Site Name,Date with time,Result,Qualifier,Original Value,Icons,aggregation_year,date_processed,level
0,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T00:00:00-08:00,3.3,,3.3,place,2023,2025-11-25T02:37:57.931181,green
1,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T01:00:00-08:00,1.0,,1.0,place,2023,2025-11-25T02:37:57.931181,green
2,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T02:00:00-08:00,0.1,,.1,place,2023,2025-11-25T02:37:57.931181,green
3,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T03:00:00-08:00,0.0,,.0,place,2023,2025-11-25T02:37:57.931181,green
4,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T04:00:00-08:00,0.0,,.0,place,2023,2025-11-25T02:37:57.931181,green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-12-30T19:00:00-08:00,1.2,,1.2,place,2023,2025-11-25T02:37:57.931181,green
980,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-12-30T20:00:00-08:00,2.1,,2.1,place,2023,2025-11-25T02:37:57.931181,green
981,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-12-30T21:00:00-08:00,2.7,,2.7,place,2023,2025-11-25T02:37:57.931181,green
982,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-12-30T22:00:00-08:00,4.5,,4.5,place,2023,2025-11-25T02:37:57.931181,green
983,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-12-30T23:00:00-08:00,5.3,,5.3,place,2023,2025-11-25T02:37:57.931181,yellow

In [23]:
hs2name_pattern="apcd_h2s_*.parquet"
hs2name_pattern="*.parquet"
hs2_files=f"s3://{bucket}/{hs2s_base}/{hs2name_pattern}"
s3_setup="""CREATE SECRET (
    TYPE s3,

    ENDPOINT 'oss.resilientservice.mooo.com',
    URL_STYLE 'path'
);
"""
con = duckdb.connect()
con.execute(s3_setup)
hs2_data2=con.read_parquet(hs2_files).df()
hs2_data2

,SiteName,Latitude,Longitude,AgencyName,LongName,Parameter,Site Name,Date with time,Result,Qualifier,Original Value,Icons,aggregation_year,date_processed,level
0,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T00:00:00-08:00,3.3,,3.3,place,2023,2025-11-25T02:37:57.931181,green
1,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T01:00:00-08:00,1.0,,1.0,place,2023,2025-11-25T02:37:57.931181,green
2,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T02:00:00-08:00,0.1,,.1,place,2023,2025-11-25T02:37:57.931181,green
3,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T03:00:00-08:00,0.0,,.0,place,2023,2025-11-25T02:37:57.931181,green
4,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T04:00:00-08:00,0.0,,.0,place,2023,2025-11-25T02:37:57.931181,green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11811,IB CIVIC CTR,32.576139,-117.115361,San Diego APCD,Imperial Beach Civic Center,07 H2S PPB,IB CIVIC CTR,2024-12-30T19:00:00-08:00,17.8,,17.8,place,2024,2025-11-25T02:37:40.288369,yellow
11812,IB CIVIC CTR,32.576139,-117.115361,San Diego APCD,Imperial Beach Civic Center,07 H2S PPB,IB CIVIC CTR,2024-12-30T20:00:00-08:00,16.1,,16.1,place,2024,2025-11-25T02:37:40.288369,yellow
11813,IB CIVIC CTR,32.576139,-117.115361,San Diego APCD,Imperial Beach Civic Center,07 H2S PPB,IB CIVIC CTR,2024-12-30T21:00:00-08:00,9.3,,9.3,place,2024,2025-11-25T02:37:40.288369,yellow
11814,IB CIVIC CTR,32.576139,-117.115361,San Diego APCD,Imperial Beach Civic Center,07 H2S PPB,IB CIVIC CTR,2024-12-30T22:00:00-08:00,5.0,,5.0,place,2024,2025-11-25T02:37:40.288369,yellow
11815,IB CIVIC CTR,32.576139,-117.115361,San Diego APCD,Imperial Beach Civic Center,07 H2S PPB,IB CIVIC CTR,2024-12-30T23:00:00-08:00,1.6,,1.6,place,2024,2025-11-25T02:37:40.288369,green